spring:
#  boot:
#    admin:
#      client:
#        enabled: true
#        url: http://microservice-monitoring:8080
#        instance:
#          service-url: http://microservice-order:8080

#  liquibase:
#    enabled: true
#    drop-first: true
#    change-log: classpath:database-order-changelog.xml
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    open-in-view: false



test:
  name: top-application-mortgage-product-process
